### ISSUE TITLE
Using backdrop-filter disables window transparency in affected areas

### ISSUE THREAD

**Issue by xvwyh** [AryToNeX/Glasscord#17]
**Describe the bug**
Loving the look achieved with this tool, thank you for making it. I tried to take it one step forward by making various context menus and other popups glassy as well, and achieving that using `backdrop-filter` CSS property is the best solution, but - oh no! - it causes issues with window transpancy:
![image](https://user-images.githubusercontent.com/43143822/79673121-303a3580-81e0-11ea-8b0a-4e1f0b40db6d.png)
Basically all the pixels affected by the element that has `backdrop-filter` (including, seemingly, the shadow) become fully opaque.

I have no idea if it's possible to fix this, this might be a kink of whatever embedded browser Discord is using.

**To Reproduce**
1. Use the provided example theme with `blurbehind` mode
2. Add to it the following style (`.da-contextMenu` might need some suffix, BandagedBD provides suffixless aliases):
```css
.da-contextMenu {
    backdrop-filter: blur(8px);
    background: rgba(24, 25, 28, 0.25);
}
```
3. Open a context menu anywhere

**Expected behavior**
Window background should remain transparent, backdrop filter should be applied to window contents.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.15063), build 1703
 - Discord version: 0.0.306 Stable 58439 (3e2271b)
 - Glasscord version: 0.0.6
 - Other Discord mods used: BandagedBD 0.3.4 (65bf2ab)

**Comment by AryToNeX** [comment]
Yeah, that's a limitation of doing native composition. You see, the window actually doesn't know what's behind it, so it can't sample it. It can't sample transparency either for some reason (aka blame it on Blink). Sadly there's nothing I can do here.

**Comment by xvwyh** [comment]
Of course I don't expect `backdrop-filter` to blur the contents of my desktop (DWM takes care of that), just the contents of the rendered HTML page, but I guess somewhere in the equation destination alpha channel is getting lost. If the background is not opaque, I can see how it might be difficult to composite transparent image (blurred backdrop) over another transparent image (original backdrop) - original will probably be poking through the overlaid image in places where it's not opaque. Come to think of it, I reckon even Photoshop has similar issues where background transparency gets lost with some blending modes.
