### ISSUE TITLE
Crashing on startup on Arch Linux

### ISSUE THREAD

**Issue by depsterr** [AryToNeX/Glasscord#19]
**Describe the bug**
Upon starting the software it crashes and showing an error message. 

**To Reproduce**
1. Install according to instructions
2. Restart discord

**Expected behavior**
Successful launch

**Screenshots**
[screenshot of error message](https://i.imgur.com/iVIA5VU.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux (Kernel 5.6.3-arch1-1)
 - Discord version: Discord 0.0.10
 - Glasscord version: 0.0.7.1
 - Other Discord mods used: EnhancedDiscord

**Additional context**
I am sure that I have `xorg-xprop` installed and that I followed the instructions properly. My window manager is dwm and my compositor is picom.

**Update**
Upon trying version 0.0.6 instead it worked perfectly.

**Comment by AryToNeX** [comment]
You aren't in an x11 session are you?

**Comment by depsterr** [comment]
@AryToNeX I am

**Comment by AryToNeX** [comment]
Well, this is the first time someone has an error like this on i3 (?) on x11 on arch

**Comment by depsterr** [comment]
My window manager is dwm, not i3. But yeah, pretty weird in that case. Have you got any clue if you changed anything between 0.0.6 and 0.0.7.1 where the error message says it crashed?

**Comment by Zantox** [comment]
Same thing happened to me on Arch Linux as well, but I use i3-gaps and picom, and BeautifulDiscord. Version 0.0.6 works.

**Comment by AryToNeX** [comment]
To be fairly honest with you, I needed to split some code and this may be the cause of this issue

**Comment by depsterr** [comment]
@AryToNeX it is installed through the package manager from the official repositories

**Comment by depsterr** [comment]
@AryToNeX I copied the command that gets run and ran it manually
```
cat test.sh
xprop -id $(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}') -notype -f _NET_WM_NAME 8t | grep "_NET_WM_NAME = " | cut --delimiter=' ' --fields=3 | cut --delimiter='"' --fields=2
sh test.sh
dwm
```

and it seems to be working properly.

**Comment by AryToNeX** [comment]
Okay, now this is strange... I don't know, try to package and use the asar from the master branch?? You can do so via a normal npm install

**Comment by depsterr** [comment]
The master branch works for me now, thanks for the fix!
