### ISSUE TITLE
Doesn't work with Powercord

### ISSUE THREAD

**Issue by j0w0** [AryToNeX/Glasscord#20]
**Describe the bug**
Glasscord does not work when Powercord is installed

**To Reproduce**
1. Install Powercord (Need Discord Canary)
2. Add glasscord.asar to index.js
3. Boot Discord Canary

**Expected behavior**
Proper launch

**Screenshots**
https://i.imgur.com/UplAYOt.png

**Desktop (please complete the following information):**
 - OS: Arch Linux, KDE Plasma 5, KWin WM/Compositor
 - Discord version: Canary 58883 (6dea2a8)
 - Glasscord version: 0.0.7.1
 - Other Discord mods used: Powercord v2 (2a48663)

**Additional context**
This could also be a Discord Canary problem (Powercord only supports canary)

**Comment by j0w0** [comment]
Update, read other issue which used 0.0.6 to fix the problem, but I got the same error when using the older version.

**Comment by MasicoreLord** [comment]
Powercord isn't currently compatible w/ glasscord.
There's a conflict that has yet to be pinpointed, and it would be up to the maintainer/dev of powercord to fix it, similar to BandagedBD (which is fixed now)
@j0w0

**Comment by AryToNeX** [comment]
We are not actively supporting Canary, and we don't plan to do so now since this is alpha software.
