### ISSUE TITLE
Muted channels are nearly unreadable

### ISSUE THREAD

**Issue by r3muxd** [AryToNeX/Glasscord#23]
**Describe the bug**
When you mute a channel, the color on the blurred background on dark theme makes it nearly unreadable.

**To Reproduce**
1. Mute channel on dark theme
2. See error

**Expected behavior**
Channel name being visible

**Screenshots**
https://media.discordapp.net/attachments/114407194971209731/707043223993843822/unknown.png

**Desktop (please complete the following information):**
 - OS: Linux
 - Discord version: Latest
 - Glasscord version: Latest alpha
 - Other Discord mods used: BetterDiscord with no themes applied

**Additional context**

**Comment by dudeamax99** [comment]
This is an issue with the theme you chose and your background, not a glasscord issue. Pick a different theme or change your background.

**Comment by dudeamax99** [comment]
You're using a theme in that screenshot, the default glasscord one. It just makes it transparent, it's cause of your background that you can't change anything.

**Comment by MasicoreLord** [comment]
It's not an issue w/ glasscord, it's in the default theme, in not trying to minimize the chance stuff becomes unreadable on top of the blurred background, no matter what is behind the window (as it's not just your desktop that could show through, it's anything that's behind the window, including other windows)

**Comment by AryToNeX** [comment]
This is not really a bug; besides, the example theme is nothing but a reference theme to show others what this tool is about.
Feel free to change the values in the CSS though (and maybe change the whole theme as a consequence, so we'll have more themes in the showcase section)
