### ISSUE TITLE
I need some help getting to work

### ISSUE THREAD

**Issue by tjw0lf** [AryToNeX/Glasscord#3]
I need some help

I downloaded the github Glasscord

I put the glasscord.js file in  $HOME/.config/discord/x.x.x/modules/discord_desktop_core/

started up discord but i have no effact. Can you help me out please thank you

**Comment by 3l0w** [comment]
you have to modify the index.js file.
And also you have to inject the css through discord

**Comment by tjw0lf** [comment]
I did modify index.js file

And also you have to inject the css through discord? what do i do

**Comment by AryToNeX** [comment]
Marked as invalid.
There's a Discord server for support request. This issue tracker is for bug requests or feature requests only.

**Comment by tjw0lf** [comment]
OK
