### ISSUE TITLE
Emoji panel background is nearly fully transprent

### ISSUE THREAD

**Issue by SomePersonFromMars** [AryToNeX/Glasscord#30]
**Describe the bug**
The emoji/gif panel is transparent so it's hard to choose the right emoji.

**To Reproduce**
Just open the emoji panel.

**Expected behavior**
The panel background should be less transparent or not transparent at all.

**Screenshots**
![Annotation 2020-05-12 131315](https://user-images.githubusercontent.com/42392219/81679174-5905c180-9452-11ea-97e9-5f3f8490db04.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.18363)
 - Discord version: Stable 59984 (f3380b6)
 - Glasscord version: Alpha 0.0.7.1
 - Other Discord mods used: plain EnhancedDiscord

**Additional context**
...

**Comment by depsterr** [comment]
see #23

**Comment by AryToNeX** [comment]
@depsterr where are you?? why did you leave our discord???????? we're doing cool stuff right now!!!

btw issue fixed in the glasstron branch
