### ISSUE TITLE
No Titlebar

### ISSUE THREAD

**Issue by jomovo** [AryToNeX/Glasscord#31]
**Describe the bug**
I have no titlebar in discord

**To Reproduce**
It happens everytime I start discord

**Expected behavior**
I should have a titlebar

**Screenshots**
![Discord no Titlebar](https://user-images.githubusercontent.com/33429636/81809689-08f63000-9522-11ea-8a59-d8553c303c39.png)

**Desktop (please complete the following information):**

 - OS:Debian 10
 - Discord version: 0.0.10
 - Glasscord version:0.0.7.1
 - Other Discord mods used:LinuxED

**Additional context**
My glasscord_config.json:
```
{
  "windowProps": {
    "frame": false
  },
  "modules": {
    "Discord": {
      "enabled": true,
      "config": {
        "titlebar": "native"
      }
    }
  }
}
```
I have in my css file:
`--glasscord-titlebar: native;`

**Comment by AryToNeX** [comment]
you should set --glasscord-titlebar to "linux" if you're on linux

**Comment by jomovo** [comment]
Ok, I have done that, but I still do not have a titlebar in discord.

**Comment by AryToNeX** [comment]
delete your configuration files and try again; you broke your installation

**Comment by jomovo** [comment]
Thank you! It worked.

**Comment by jomovo** [comment]
I just noticed it resets to native every time I restart Discord. I only get the titlebar once when I delete the config file.

**Comment by AryToNeX** [comment]
that's because you left it to native in your css file, pretty much
