### ISSUE TITLE
Add instructions on how to use CSS loader

### ISSUE THREAD

**Issue by gabrc52** [AryToNeX/Glasscord#33]
I've just installed Glasscord on Discord but I don't know how to enable the blurred theme.

The only instruction says:

> If you're using Glasscord's own CSS loader, you can configure it easily by editing the configuration files

**Comment by AryToNeX** [comment]
you didn't quote-to-quote the entire paragraph; we say where are the config files too.
If you just went there to check what's inside then you could've realized that everything after that point is self explanatory.

**Comment by gabrc52** [comment]
Yeah, but what do I have to change in the config file? I couldn't find documentation for the config file, I'm sorry

**Comment by AryToNeX** [comment]
Again, you should then check the contents of those files. Specifically, look the contents of the folder with the same name as your application.
If you're using Discord then remember that editing Glasscord configuration files is pointless as you need a client mod to use it (EnhancedDiscord/BandagedBD/Powercord (limited support)). Then you should load a theme from that client mod and Glasscord will just pick up the changes and do the magic.

**Comment by krusli** [comment]
The latest release (8 days ago) predates this commit (https://github.com/AryToNeX/Glasscord/commit/5c13665c13b5e655aa789a242438a91e8e449908) that fixes the Glasscord CSS loader for Discord.

I built the latest version myself and the config (~/.config/glasscord/discord/config.json5 for this version) now has a new CSSLoader: true prop.

I'm on the same boat and am not sure where to add the CSS path.
