### ISSUE TITLE
"acrylic" blur mode on Windows makes the window very laggy when dragged around

### ISSUE THREAD

**Issue by NurMarvin** [AryToNeX/Glasscord#34]
**Describe the bug**
When having the `--glasscord-win-blur` CSS variable set to `acrylic`, the window drags very weirdly and slow.

**To Reproduce**
1. Set `--glasscord-win-blur` to `acrylic`
2. Drag window around
3. Observe

**Expected behavior**
Window should move normally instead of lagging.

**Video**
https://youtu.be/0GV_3rJ2ECs

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.18363)
 - Discord version: [BUILD INFO] Release Channel: canary, Build Number: 60935, Version Hash: db877b44594a4b7a6cc8989fa137ff0cfda25e3e
 - Glasscord version: 0.2
 - Other Discord mods used: Powercord

**Additional context**
For whatever reason when trying to record the bug with a screen recorder, the video only picks up certain parts, normally the window slides to certain locations very slowly while you can't do anything else on your computer.

**Comment by dudeamax99** [comment]
Bug with windows, we can't fix. Mentioned in README https://github.com/AryToNeX/Glasscord#--glasscord-win-blur-windows

**Comment by NurMarvin** [comment]
Ah, my bad, I checked all the issues for any mentions of any issue like this but didn't find anything but forgot to check the README as well, so I just assumed no one was aware.
Considering it's not fixable, I'll close this issue.
