### ISSUE TITLE
Installing for Discord on Windows 10

### ISSUE THREAD

**Issue by cutieshy** [AryToNeX/Glasscord#42]
I set this up pretty easily a couple months ago on linux but I've switched back to Windows for a bit and I can't figure this out. I remember I installed it on a friend's PC and it was pretty easy but it feels like there's something missing from the readme now.

It just says "find the app.asar" and for discord I don't remember there being one, I know where the core.asar is but using that folder and editing the package.json just results in discord crashing. If you could re-add the parts (I think) you removed could you send them here, or just help me out please. Thank you!

**Comment by PoorPocketsMcNewHold** [comment]
https://github.com/AryToNeX/Glasscord#how-do-i-install-it

Read the Readme.md. It explicitly asks if there is an app.asar OR app folder, in which the installation method is different.

**Comment by AryToNeX** [comment]
Are you referring to [these old instructions](https://github.com/AryToNeX/Glasscord/tree/c3688cfa089eb61031f10175b81ea127ce982746#discord-instructions)? They're old and unsupported, but Glasscord can still be injected this way (although it's not recommended anymore to do so)

**Comment by AryToNeX** [comment]
I am closing this as it's inactive by now.
