### ISSUE TITLE
Latest version of Discord Canary and possibly relevant PowerCord build breaks glasscord.

### ISSUE THREAD

**Issue by redalpha01** [AryToNeX/Glasscord#49]
**Describe the bug**
Latest Discord Canary seems to have either broken GlassCord  OR the fix powercord implemented to work with latest version broke GlassCord (unsure as which)

Processes would open but not the window or taskbar icon.

Upon further research into that last powercord commit, it seems unlikely that it is an issue caused by powercord considering  [this](https://github.com/powercord-org/powercord/commit/64e94b40dc89fddb068be387262a7ca3f543b21f) was the patch

**To Reproduce**
1. Update to Canary 63843 
2. (Optional or at least untested without it) Install the latest build of powercord
3. Install Glasscord following installation instructions.

**Expected behavior**
Discord opens correctly with latest Canary and powercord build.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Discord version: Canary 63843 
 - Glasscord version: Release 0.2
 - Other Discord mods used: Powercord commit [64e94b40dc89fddb068be387262a7ca3f543b21f](https://github.com/powercord-org/powercord/commit/64e94b40dc89fddb068be387262a7ca3f543b21f)

**Comment by AryToNeX** [comment]
@Bowser65
FUCK

**Comment by AryToNeX** [comment]
Honestly, I don't think this bug is fixable right now. Thing is, I don't know how to handle this one, so I will just let it be for the time being.
That said, if someone wants to issue a pull request, I will gladly accept it.

I just hope it won't break on stable Discord sooner than expected.

**Comment by AryToNeX** [comment]
Fixed with latest commit!
this was really an oversight!
