### ISSUE TITLE
Glasscord broke after discord 0.0.11 update on linux

### ISSUE THREAD

**Issue by RawGamingYT** [AryToNeX/Glasscord#52]
Glasscord just won't work in anyway now and when I try to apply a theme it just goes all transparent. I assume an update is needed?

1. Install glasscord on an discord installation
2. load a css file containing glasscord options

Expected behavior: 
Everything should work fine and discord would load normally.

Screenshots:
![image](https://user-images.githubusercontent.com/56405082/89574200-c3cc5c00-d7f9-11ea-903a-a1dde44412f1.png)

Desktop:
 - OS: Arch linux (DE: Kde plasma 5)
 - Discord version: 0.0.11-1
 - Glasscord version: 0.2
 - Other Discord mods used: BeautifulDiscord (to inject css theme)

Titlebar sometimes change when you unload the css theme again.

**Comment by Bamentix** [comment]
Same happens on Windows with version 0.0.307.

**Comment by AryToNeX** [comment]
I cannot reproduce this issue. Please make sure that your CSS loaders are updated and that Glasscord is still injected properly. If you still cannot make it work, then, please give the `master` branch a shot.

Either way, I currently cannot understand what's wrong with Glasscord (since it still works on my machine)

**Comment by Bamentix** [comment]
Yeah I just found out that BeautifulDiscord is broken since the new update. I cant find any other css only loader so I have to wait until they fix the issue.

**Comment by RawGamingYT** [comment]
> Yeah I just found out that BeautifulDiscord is broken since the new update. I cant find any other css only loader so I have to wait until they fix the issue.

but it seems that beautifuldiscord ain't being actively developped recently

**Comment by RawGamingYT** [comment]
i'll close this i guess

**Comment by AryToNeX** [comment]
sad

**Comment by szv0** [comment]
Beautifuldiscord updated and can inject css, but glasscord seems to still not work.

**Comment by RawGamingYT** [comment]
It works if you sue Enhanced discord which is what i did, it diden't work yesterday but i manually changed something from a pull request that now has been merged and you can probably install it normally using LinuxED or whatever system you are on

**Comment by manilarome** [comment]
Glasscord broke after updating to 0.0.11 on Archlinux.

<details>
<summary> Here's the log </summary>
<br>
[77388:0810/092417.098910:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command<br>
(node:77351) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.<br>

  at WebFrame../lib/renderer/api/web-frame.ts.WebFrame.<computed> [as executeJavaScript] (electron/js2c/renderer_init.js:1807:33)
    at electron/js2c/renderer_init.js:3067:43
    at electron/js2c/renderer_init.js:2696:40
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:2696:9)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:2470:16)
(node:77351) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame../lib/renderer/api/web-frame.ts.WebFrame.<computed> [as executeJavaScript] (electron/js2c/renderer_init.js:1807:33)
    at electron/js2c/renderer_init.js:3067:43
    at electron/js2c/renderer_init.js:2696:40
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:2696:9)
    at EventEmitter.emit (events.js:203:13)
 at Object.onMessage (electron/js2c/renderer_init.js:2470:16)
(node:77351) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:77351) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:77351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:77351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Glasscord Featured Modules] Matching files for featured/discord/discord_titlebar.js.

</details>

**Comment by AryToNeX** [comment]
@manilarome that log seems related to internal electron stuff only; I need something else to debug this issue; sorry
