### ISSUE TITLE
Discord looks like a browser-discord after applying glasscord

### ISSUE THREAD

**Issue by asdfqwerty0123** [AryToNeX/Glasscord#55]
Sorry for my bad English, but I'll be glad if you understand that I'm not good at English.

**Describe the bug**
Let me describe with this picture.
![스크린샷(9)](https://user-images.githubusercontent.com/43396722/90313009-d81fff80-df43-11ea-94e0-c8ed01c617b6.png)
First, there is no title bar on the top.
Second, there is a Discord download button on the left.
Basically it looks like a discord in a browser. But as you see, it's not a browser-discord.

**To Reproduce**
1. Create an app folder in C:\Users\\(username)\AppData\Local\Discord\app-0.0.307\resources
2. Open Git bash by right-click, then type `asar ef app.asar package.json`
3. Move `package.json` to app folder
4. Also move `glasscord.asar` to app folder.
5. Change "main" value in `package.json` to `glasscord.asar`
6. Quit Discord and re-opened and got this bug.
However, themes are working properly.
![image](https://user-images.githubusercontent.com/43396722/90313411-5631d580-df47-11ea-8100-bd78a7697b99.png)

On Discord version 0.0.306, this worked normally. But Discord got an upgrade to 0.0.307, and I realized that glasscord has gone(?)
So I re-downloaded `glasscord.asar` and tried to apply glasscord on 0.0.307, and got this bug.

**Expected behavior**
Well, it should work like a native Discord app, but it works like a browser-Discord, so... yes.

**Desktop**
 - OS: Windows 10 (build 19041.450)
 - Discord version: 0.0.307 (latest stable)
 - Glasscord version: 0.2 (latest)
 - Other Discord mods used: No.

Sorry for my bad English again :(

**Comment by AryToNeX** [comment]
How did you apply the theme if you claim to only be using Glasscord?
By the way, Glasscord 0.2 is not supported anymore. I should maybe write it down.

**Comment by asdfqwerty0123** [comment]
I just put the css file into AppData₩Roaming₩glasscord₩glasscord₩CSSLoader₩ (i dont know if i wrote it correctly)
and changed theme path to above

And I see, I'll wait 'till the next release update
