### ISSUE TITLE
Discord Canary Javascript error boot

### ISSUE THREAD

**Issue by Basilou-R** [AryToNeX/Glasscord#57]
**Javascript error boot discord**

**To Reproduce**
1. Install Glasscord
2. Launch Discord

**Screenshots**
![image](https://user-images.githubusercontent.com/17341929/92639453-1a86f300-f2dc-11ea-8967-d41ddb4b7a57.png)

**Desktop (please complete the following information):**
 - OS: W10 1090 latest build
 - Discord version: Canary 0.0.274 (clean install)
 - Glasscord version: v0.9999.9999
 - Other Discord mods used: Nope

**Comment by AryToNeX** [comment]
This is a common installation error. Please review your broken installation.
