### ISSUE TITLE
Glasscord Example Theme isn't loading the correct css.

### ISSUE THREAD

**Issue by algertc** [AryToNeX/Glasscord#58]
Discord Stable 67825
Manjaro KDE 
Glasscord version: Interim release before v1.0 (v0.9999.9999)
No other plugins currently in use

I am using the included Glasscord css loader. It does not seem to be loading properly. 
Current look: https://imgur.com/vkyEefr.png

I have glasscord installed in /usr/lib/electron/resources/app, with the json named "package.json"
screenshot of path and files: https://imgur.com/Xnlljx5.png
screenshot of package.json contents: https://imgur.com/jOgcWvm.png

The readme intructions also reference this directory: /.config/discord/0.0.12/modules/discord_desktop_core. I have not changed anything here. Here is a screenshot of the contents: https://imgur.com/noYEGmb.png

I saw issue #50 which looks visually similar to my current discord, which leads me to believe I screwed up the installation. Apologies in advance if this is the case.

**Comment by PoorPocketsMcNewHold** [comment]
Uninstall Discord from the community repos, and install one from the AUR that doesn’t depend on electron.

On Arch _(And Manjaro too)_, they do a weird thing with most of the electron apps, which require electron to be installed. Basically, what they do, is that they don’t install the actual discord binaries, but they instead download electron, and the required files to load the wished electron app into it, a bit as a ¨dev test live mode¨. However, Glasscord require making modifications to the actual compiled files to be effective. The only reason I’ve found for why they distribute those as it is, is only for size reduction, as every electron apps comes each with their own ¨electron browser¨, even if they could utilize the already available libs on your system. However, only having a few electron applications install make this actually weight more on your storage, and doesn’t include the performance improvement, optimizations and stability that a compiled application would give.

Requesting to close this Issue.

**Comment by algertc** [comment]
AUR version working fine, electron was indeed the problem. 
Thanks for your help.
