### ISSUE TITLE
Discord: Screen Sharing Unavailable

### ISSUE THREAD

**Issue by Neightro** [AryToNeX/Glasscord#60]
**Describe the bug**
When attempting to share your screen, a message box appears stating that screen sharing is unavailable and instructing the user to download the desktop client.

**To Reproduce**
1. Join a voice chat
2. Click on 'Screens'
3. A message box appears, which reads "Screen Sharing Unavailable: Download the Discord Desktop app to use screen sharing!"

**Expected behavior**
The program presents the user with a list of applications or screens to stream.

**Screenshots**
![20201007_143250](https://user-images.githubusercontent.com/23202923/95390849-dff88200-08aa-11eb-9d3f-8ef1dab1ad74.png)

**Desktop**
 - OS: Manjaro Linux
 - Discord version: 0.0.12 (latest Manjaro package version)
 - Glasscord version: interim release (0.999…)
 - Other Discord mods used: None

**Comment by AryToNeX** [comment]
This is not a bug, but rather an installation error. This and other bugs happen when you are not injecting Glasscord onto Discord properly. Please read the README carefully; and please only report bugs that happen on the actual `master` branch.

**Comment by Neightro** [comment]
I completed each step as carefully as I could, and rereading it again there isn't anything apparent to me that I missed. is there any chance you could help me find which step I missed?

I created the app folder, used asar to extract package.json from app.asar, and moved both package.json and the latest release of glasscord.asar into the folder. I modified package.json to point to glasscord.asar.

After installation, my directory tree is as follows:

```
/opt/discord/resources
├── app
│   ├── glasscord.asar
│   └── package.json
├── app.asar
├── bootstrap
│   └── manifest.json
└── build_info.json
```
My package.json is:
```
{
  "name": "discord",
  "description": "Discord Client for Desktop - Bootstrapper",
  "main": "./glasscord.asar",
  "private": true,
  "dependencies": {
    "mkdirp": "^0.5.1",
    "request": "2.88.0",
    "rimraf": "^2.6.3",
    "yauzl": "^2.10.0"
  },
  "devDependencies": {
    "devtron": "1.4.0"
  }
}
```

**Comment by ADoesGit** [comment]
forgot to make ``package.original.json``

**Comment by AryToNeX** [comment]
> forgot to make `package.original.json`

That does not apply to Discord without modifications.
The real problem is that the interim release only works when coupled with other client mods such as BetterDiscord or Powercord.

**Comment by ADoesGit** [comment]
oh lol, didn't know that

**Comment by Neightro** [comment]
Thank you for the insight! I will look into one of the aforementioned client mods.

Worst case scenario, with full understanding that bug reports will not be accepted for that version, would installing Beta v0.2 be a reasonable course of action?

**Comment by AryToNeX** [comment]
> Thank you for the insight! I will look into one of the aforementioned client mods.
> 
> Worst case scenario, with full understanding that bug reports will not be accepted for that version, would installing Beta v0.2 be a reasonable course of action?

Beta 0.2 is unsupported and it lacks many security fixes
