### ISSUE TITLE
Don't work for me [Ubuntu 20.04.1 LTS, 64 bits]

### ISSUE THREAD

**Issue by TheGlu3guy** [AryToNeX/Glasscord#62]
Hello I am a noob in this and I have been trying to make this work for almost 2 days but it doesn't work and I am too dumb to figure it out. I don't know if it's the right place to seek for help so I will delete it if it isn't.

So I followed the installation tutorial by going to /usr/share/discord/resources, creating a app folder, extracting the package.json from the app.asar, modifying the main which make me end up with this content :
```
{
  "name": "discord",
  "description": "Discord Client for Desktop - Bootstrapper",
  "main": "./glasscord.asar",
  "private": true,
  "dependencies": {
    "mkdirp": "^0.5.1",
    "request": "2.88.0",
    "rimraf": "^2.6.3",
    "yauzl": "^2.10.0"
  },
  "devDependencies": {
    "devtron": "1.4.0"
  }
}
```
putting glasscord.asar in the app folder and then restard discord. It didn't worked so I tried every other option in the tutorial like naming the file package.original.json, or putting require("path/to/app/glasscord.asar") in top of it but nothing did it.
Although it seems to have acknowledge it because a "glasscord" folder appeared in my .config and a "discord" folder appeared in this glasscord folder.
Can you help me finding what have I done wrong or missed ?

Thanks in advance :)

**Comment by AryToNeX** [comment]
Hey! Sorry if it seems too complicated but sure, we can help you.
Please head over to our Discord server, other users will help you set that up!
Also, please kindly provide a recording on all the steps you did and how did you do those, so we can point out exactly what is missing to you. It is that simple!
