### ISSUE TITLE
Glasscord seems to make Discord client think its running in a browser.

### ISSUE THREAD

**Issue by StuntVist** [AryToNeX/Glasscord#64]
**Describe the bug**
Glasscord seems to make the client think its running in a browser, resulting in no microphone or screenshare functionality. Everything else seems to work flawlessly.

**To Reproduce**
Installing glasscord with an app.asar file present via creating an app folder and extracting package.json, placing that and glasscord.asar in the app folder and changing main to glasscord.asar in package.json and then relaunching Discord results in said bug. 
Tried clearing cahce, config files, reinstalling everything completely fresh, same issue. Simply installing glasscord without anything else seems to be enough.

**Expected behavior**
Expecting the client to still think its a client and not running in the browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/68554720/98557240-9dacd100-22ac-11eb-9263-0ba9c11eef5d.png) 
Before removal of glasscord with css injected (gave me the same issue without having any css injected)

![image](https://user-images.githubusercontent.com/68554720/98557582-10b64780-22ad-11eb-8a94-02ae83ad6865.png)
After removal of glasscord. 

**Desktop:**
 - OS: Linux
 - Discord version: 0.0.12
 - Glasscord version: 0.9999.9999
 - Other Discord mods used: none

**Additional context**
Not entirely sure if it's something simply on my end but I'm also fairly clueless on how to debug this.

**Comment by AryToNeX** [comment]
Related issues: #55 and #60. This is an installation issue. Please check your installation steps and make sure they all are correct. If you still find yourself in this situation, you might want to install a client mod like Powercord or BandagedBD first, as Glasscord is compatible and tested with those other mods in place.

**Comment by StuntVist** [comment]
Still seem to encouter the same issue. I tried dowloading canary and installing powercord before installing glasscord as per guide and that resulted in glasscord not doing anything at all.
