### ISSUE TITLE
Composition effects not working under nvidia drivers

### ISSUE THREAD

**Issue by RotatingBuffalo** [AryToNeX/Glasscord#65]
Transparency worked flawlessly until I changed from nouveau to nvidia, and now the glasscord default theme only has the curved corners and no composition effects. I've tried enabling/disabling every relevant setting inside of discord, and looking in nvidia-settings didn't seem to show anything useful either.

**Comment by sodahead** [comment]
buy amd or switch to nouveau

**Comment by RotatingBuffalo** [comment]
true

**Comment by AryToNeX** [comment]
Are you a Discord Canary user? If so, blame Electron.They messed up stuff recently and transparency in Linux is a no-go, not even in AMD.
Sadly and obviously this is an issue not fixable in Glasscord's scope.

**Comment by RotatingBuffalo** [comment]
I'm not on canary, it's the current stable discord release. Glasscord works perfectly on nouveau and doesn't on nvidia. I've checked, and it's happening with or without hardware acceleration, under OpenGL, if any of that is useful to you.

**Comment by ShayBox** [comment]
I'm still able to get it to work using glasscord, enabling bbd transparency, enabling a glasscord theme, while using stable discord, latest kernel and nvidia drivers.

**Comment by AryToNeX** [comment]
I don't know what to say.. Nvidia is at it again, guys.
Glasscord won't directly talk to the driver in any occasion; but it will talk to KWin on KDE and Deepin, and there's no way it won't since this behaviour has been tested over and over and I can confirm it works.. Something is wrong, but it has nothing to do with Glasscord. It could be an Electron bug though.

**Comment by PoorPocketsMcNewHold** [comment]
I can confirm it still work for me. Feren OS (Ubuntu based). 5.4.76-xanmod1. Proprietary Nvidia 455 drivers. You aren’t using the latest kernel, isn’t it? Don’t know how broken it is on it and if it can cause issues with Kwin in itself. https://forums.developer.nvidia.com/t/nvidia-driver-not-yet-supported-for-linux-kernel-5-9/157263

![](https://user-images.githubusercontent.com/13170204/99188849-0c2eda80-2756-11eb-94e2-d8fd8606bf2e.png)

**Comment by ShayBox** [comment]
I'm using KDE with kwin-lowlatency, also the drivers were updated a week after that article, Nvidia drivers work fine on latest kernel.

**Comment by ShayBox** [comment]
Update: I got it working, I tried the package.original.json thing, that doesn't work apparently, I had to add the require line to index.js, now it works perfectly.
