### ISSUE TITLE
Glasscord-tint red and blue values swapped

### ISSUE THREAD

**Issue by AjHill15** [AryToNeX/Glasscord#7]
Changing the --glasscord-tint value has the opposite effect when changing the R and B values.

Setting the values to (255,0,0,1) changes the window to blue
Setting the values to (0,0,255,1) changes the window to red

Green values works fine.

Tested buy changing the values in the example theme, line 27.

**Comment by AryToNeX** [comment]
There is not enough information. I don't know what is your OS and I don't know if you are on the latest version. Please, use the issue template!

**Comment by AryToNeX** [comment]
Fixed in b1c3383
