### ISSUE TITLE
New Discord update broke glasscord.

### ISSUE THREAD

**Issue by OhItsTom** [AryToNeX/Glasscord#76]
Discord update app-0.0.309 broke both betterdiscord and glasscord.
Upon reinstalling/repairing betterdiscord, glasscord refused to boot.
Having reinstalled glasscord, upon launching discord, the client is treated as if its being used in a browser with the warning box somewhere along the lines of "install our desktop app for improved yada yada yada". 
It also disabled better discord.

 - OS: Windows 64bit update 19041.572
 - Discord version: 0.0.309
 - Glasscord version: Latest
 - Other Discord mods used: Betterdiscord

**Additional context**
I understand this is supposed to be a thread for issues with glasscord, but personally i dont know how to troubleshoot whether its betterdiscord or glasscord, and i cant join the support server as the link is broken.

**Comment by sortedcord** [comment]
is it fixed yet? I installed glasscord & tried injecting it into discord, but the titlebar is missing & blur does not work. OS: mac osx 1.14.6

**Comment by AryToNeX** [comment]
macOS isn't supported anymore btw
