### ISSUE TITLE
EWC dependency missing

### ISSUE THREAD

**Issue by ntoskrnl4** [AryToNeX/Glasscord#8]
**Describe the bug**
EWC dependency is not fulfilled or something?

**To Reproduce**
I just installed ED, then tried installing this and it doesn't work..? I was using the listed release version.

**Expected behavior**
Glasscord to load :D

**Screenshots**
https://cdn.discordapp.com/attachments/504486947146694668/698013510793166898/unknown.png

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit 19.09 (10.0.18363)
 - Discord version: Stable 57725 (17125f7) Host 0.0.306
 - Glasscord version: The 1st release version
 - Other Discord mods used: ED to install.

**Additional context**
I think that's it. There's a lot of files in the repo as opposed to the ones you just need to install, but I think I got it right and it isn't working. A friend also tried installing it (Win10, save Glasscord version) and he couldn't get it either (same exact error).

**Comment by AryToNeX** [comment]
Yeah, I am dumb and I forgot to do one thing.
It's fixed in 4ef7396

**Comment by ntoskrnl4** [comment]
Yay thanks! It's working now and I'M SO IN LOVE WITH IT OMG AAAAAAAAAAA THANK YOU
