### ISSUE TITLE
Acrylic blur mode only affects the window when it is moved or resized.

### ISSUE THREAD

**Issue by HarnickA** [AryToNeX/Glasscord#9]
**Describe the bug**
Acrylic blur mode functions as expected until the Discord window is moved or resized, after which it reverts to a transparent effect, and only returns _while_ the Discord window is being moved or resized.

**To Reproduce**
Set `--glasscord-win-blur` to acrylic, reload Discord, then alter the window size or position.

**Expected behavior**
The Discord window should stay blurred after the window is moved or resized.

**Screenshots**
https://gfycat.com/altruisticfalseamericansaddlebred

**Desktop (please complete the following information):**
 - OS: Windows v.1909 (Build 18363.752)
 - Discord version: 0.0.306
 - Glasscord version: v0.0.5
 - Other Discord mods used: BandagedBD, no plugins

**Comment by AryToNeX** [comment]
I am sorry you're experiencing this issue! It seems that Windows is dumb across its versions (for example, this does not happen at all on v1903). I promise you this will be fixed on the next version 0.0.6. If you want a workaround to this problem, you could set `--glasscord-win-performance-mode` to `false`.

**Comment by AryToNeX** [comment]
I did some testing on a clean installation of Windows 10 v1909 with everything properly set and I can confirm this issue won't happen to me. I wonder if your configuration is broken, did you follow the instructions carefully?

**Comment by HarnickA** [comment]
I did recheck all of your instructions and they were correct. It's likely just something on my end. Thanks for your help and the effort you put into Glasscord!
